### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by WhiskerBiscuit** [WhiskerBiscuit/budhud#20]
I have no idea how to go about this but if I can do it eventually I will.

**Comment by jbzdarkid** [comment]
Here's a thought: I have a mac, and if it breaks for me I'll tell you. With some pointers as to the changes I have to make to fix it.

**Comment by WhiskerBiscuit** [comment]
That'd be great; I can't guarantee full support, but it was always something I at least wanted to do so the hud would be tolerable for mac users :p

**Comment by KingDuck** [comment]
So does this mean that the hud isn't tolerable for macs?

**Comment by WhiskerBiscuit** [comment]
Given @jbzdarkid's comment, I assume it largely works for Macs. If I'm wrong though, let me know.

**Comment by KingDuck** [comment]
I'll let you know if anything on my end goes awry as well.

**Comment by WhiskerBiscuit** [comment]
Thanks! If you're using the hud now, is it working properlyo r?
