### ISSUE TITLE
Update tournament hud for ready up support

### ISSUE THREAD

**Issue by WhiskerBiscuit** [WhiskerBiscuit/budhud#65]

**Comment by averagecomputerguy** [comment]
Picture for reference as to what budhud looks like with mp_tournament_readymode turned on:
![image](https://cloud.githubusercontent.com/assets/3173124/9152349/251ec6dc-3dea-11e5-9054-86c78d7e2a1a.png)

**Comment by WhiskerBiscuit** [comment]
This is what I've come up with; I'll probably leave that text there until they actually properly make it work. At the moment, I believe a map restart is required after setting the appropriate lines to make it actually allow you to ready up.

![tsuqh8x](https://cloud.githubusercontent.com/assets/509599/9152570/85b63a4a-3de3-11e5-9680-e15961c8f979.jpg)

**Comment by averagecomputerguy** [comment]
In my experience, you have to reconnect to the server if it won't let you ready up.

**Comment by WhiskerBiscuit** [comment]
Added in 15/AUGUST update.
