### ISSUE TITLE
Killstreak Counter?

### ISSUE THREAD

**Issue by TerminatorT800** [WhiskerBiscuit/budhud#69]
Wouldn't it be better if the counter was between the health and ammo, instead of being nearly invisible in the bottom right corner?
Thanks

**Comment by WhiskerBiscuit** [comment]
Since it's not vital information, I've opted to have it off in the corner so it can be checked periodically. I couldn't really find a place that looked nice and didn't block less common elements (charge meters, surf/jump timers, etc) and so I figured this would look best.
