### ISSUE TITLE
Larger Scoreboard Support

### ISSUE THREAD

**Issue by ZeekDaGeek** [WhiskerBiscuit/budhud#70]
I know 6v6 is a valid mode and all but I'm not sure why the scoreboard is only available in a 6v6 mode... Seems like it should start off as the largest and you can choose to shrink it or something. I don't know if it's supposed to be reactive or something, but it's stick as this with horrible overlapping.

http://zeekdageek.tv/ss/eJM6O.png

**Comment by WhiskerBiscuit** [comment]
If you open your menu and click the "scoreboard" button it'll set it to the larger scoreboard.

**Comment by ZeekDaGeek** [comment]
Aha, I guess I must have clicked on that button without realizing what it did. Sorry for the confusion.

**Comment by WhiskerBiscuit** [comment]
No worries! It has to do with minmode, so if your minmode setting had been changed at any point then the scoreboard would look different :)
