### ISSUE TITLE
Various text issues pertaining to arena mode

### ISSUE THREAD

**Issue by jokuperkele** [WhiskerBiscuit/budhud#72]
**Text overflow**
![Image 1](http://i.imgur.com/ZCBOP3p.jpg)

**"Your team" text shadow is in considerably smaller than the actual text.**
![Image 2](http://i.imgur.com/ZiFPh86.jpg)

**Button/item overlaps in quick loadout selection**
![Image 3](http://i.imgur.com/XK6ZIWI.jpg)

**Comment by WhiskerBiscuit** [comment]
Fixed the first two: http://i.imgur.com/ljbwrVh.jpg

**Comment by WhiskerBiscuit** [comment]
Fixed in e0b8f0a5c1f362f049d0b83bdef3e9c4488f805f

**Comment by jokuperkele** [comment]
Noice!
