### ISSUE TITLE
In-game class selection menu to look like the items page class selection?

### ISSUE THREAD

**Issue by Hautausurakoitsija** [WhiskerBiscuit/budhud#73]
The new class selection in the items/loadout page looks really cool. I was wondering if it's possible to make the in-game look and behave (active class pop-out) the same way?

![Imgur](http://i.imgur.com/S2hUN4x.jpg)

**Comment by WhiskerBiscuit** [comment]
Do you mean class selection?

**Comment by Hautausurakoitsija** [comment]
Yes. Yes I did. Sorry for the omission. :)

**Comment by WhiskerBiscuit** [comment]
After digging around a bit, I don't THINK it's possible. The latest update changes the class loadout screen very very slightly, though -- http://i.imgur.com/aYUpqcE.png
(I think it looks better)
