### ISSUE TITLE
Mvm Page

### ISSUE THREAD

**Issue by TerminatorT800** [WhiskerBiscuit/budhud#77]
Seems to have merged with the Competitive screen or something, Doesn't disappear when I press play with friends, also unable to press invite afterwards 

Images:
http://steamcommunity.com/sharedfiles/filedetails/?id=549993265
http://steamcommunity.com/sharedfiles/filedetails/?id=549993394

Not sure if this is even caused by the HUD or not

**Comment by WhiskerBiscuit** [comment]
Huh, that's odd. I tried reproducing but didn't have any luck; do you have the steps to reproduce this by chance?

**Comment by WhiskerBiscuit** [comment]
Oh, this also appears to be an older version of the hud as well; it may potentially be fixed by updating. 
The current version of the MvM lobby currently looks like this: http://i.imgur.com/VFfxM0x.png

**Comment by TerminatorT800** [comment]
I'll have a see soon and tell you if it works now or if it's still bugged.

**Comment by WhiskerBiscuit** [comment]
Great, thanks!

**Comment by TerminatorT800** [comment]
Yup It fixed it. Thanks!
